import re

class SlashCommand:
    VALID_COMMANDS = [
        "ac",
        "afk",
        "ah",
        "ai",
        "alt2tray",
        "altinvite",
        "alttray",
        "alttraysticky",
        "anglesnap",
        "anglesnapcycle",
        "antialiasing",
        "architect",
        "architectclaimtickets",
        "architectcompletemission",
        "architectexit",
        "architectfixerrors",
        "architectinvincible",
        "architectinvisible",
        "architectkilltarget",
        "architectloginupdate",
        "architectnextcritter",
        "architectnextobjective",
        "architectrepublish",
        "architectsaveandexit",
        "architectsaveandtest",
        "architectsavecompressedcostumes",
        "arena",
        "arenainvite",
        "arenalist",
        "arenalocal",
        "arenascore",
        "assist",
        "assistname",
        "attachcycle",
        "aucloginupdate",
        "auction",
        "auctionhouse",
        "autoreply",
        "autorun",
        "b",
        "backward",
        "badgegrant",
        "basedefaultsky",
        "baselightingtype",
        "baseredo",
        "baseselect",
        "baseundo",
        "beginchat",
        "bind",
        "bindload",
        "bindloadfile",
        "bindloadfilesilent",
        "bindsave",
        "bindsavefile",
        "bindsavefilesilent",
        "blackmarket",
        "bloomscale",
        "bloomweight",
        "boostconvert",
        "broadcast",
        "buildsave",
        "buildsavefile",
        "c",
        "camdist",
        "camdistadjust",
        "camreset",
        "camrotate",
        "camturn",
        "canlook",
        "cc",
        "cce",
        "ccemote",
        "center",
        "centersel",
        "chancreate",
        "chandesc",
        "changehandle",
        "chaninvite",
        "chaninvitedeny",
        "chaninvitegf",
        "chaninvitesg",
        "chaninviteteam",
        "chanjoin",
        "chanleave",
        "chanmembers",
        "chanmode",
        "chanmotd",
        "chansend",
        "chantimeout",
        "chanusermode",
        "chat",
        "chatcycle",
        "chatload",
        "chatloadfile",
        "chatoptions",
        "chatsave",
        "chatsavefile",
        "chatset",
        "ci",
        "citytime",
        "clearAttributeView",
        "clearchat",
        "clearpetnames",
        "clearRewardChoice",
        "cleartray",
        "clicktomove",
        "cmdlist",
        "coalition",
        "coalitioncancel",
        "coalitioninvite",
        "coalitionmintalkrank",
        "coalitionnosend",
        "coalitionsgmintalkrank",
        "comment",
        "compatiblecursors",
        "conprint",
        "contactfinderselectcurrent",
        "contactfindershowcurrent",
        "contactfindershownext",
        "contactfindershowprevious",
        "contactfinderteleporttocurrent",
        "contextmenu",
        "controllermodifiers",
        "controllervmouse",
        "cooldownindicator",
        "copychat",
        "costumechange",
        "ctm",
        "ctminvert",
        "ctmtoggle",
        "cursorcache",
        "customwindow",
        "customwindowtoggle",
        "debugdisableautodismiss",
        "demodump",
        "demodumptga",
        "demofps",
        "demoframestats",
        "demohideallentityui",
        "demohidechat",
        "demohidedamage",
        "demohidenames",
        "demoloop",
        "demopause",
        "demorecord",
        "demorecordauto",
        "demospeedscale",
        "demostop",
        "demote",
        "dialoganswer",
        "dialogno",
        "dialogyes",
        "disable2d",
        "dofweight",
        "down",
        "e",
        "editbase",
        "em",
        "emailheaders",
        "emote",
        "enablevbos",
        "enterbasefrompasscode",
        "enterbasefromsgid",
        "enterdoor",
        "estrange",
        "exitlaunch",
        "extramodifiers",
        "f",
        "face",
        "findmember",
        "first",
        "fl",
        "follow",
        "forward",
        "forwardmouse",
        "friend",
        "friendlist",
        "fsaa",
        "fullRelight",
        "fullscreen",
        "g",
        "gamereturn",
        "gen",
        "general",
        "getallarenastats",
        "getarenastats",
        "getcomment",
        "getglobalname",
        "getlocalinvite",
        "getlocalleagueinvite",
        "getlocalname",
        "getpos",
        "getratedarenastats",
        "gfriend",
        "gfriends",
        "ghide",
        "gignore",
        "gignoring",
        "ginvite",
        "ginvitesg",
        "gmotd",
        "gototray",
        "gototrayalt",
        "gototrayalt2",
        "gototraystray",
        "graphfps",
        "gridsnap",
        "gridsnapcycle",
        "group",
        "guide",
        "gunfriend",
        "gunfriendplayer",
        "gunhide",
        "gunignore",
        "h",
        "hardconsts",
        "hc",
        "help",
        "helpchat",
        "helpwindow",
        "hide",
        "hideall",
        "hidefriends",
        "hidegchannels",
        "hidegfriends",
        "hideinvite",
        "hideprimarychat",
        "hidesearch",
        "hideset",
        "hidesg",
        "hidetell",
        "i",
        "ignore",
        "ignorelist",
        "ignorespammer",
        "imageServer",
        "incarnateequip",
        "incarnateunequip",
        "incarnateunequipall",
        "incarnateunequipbyslot",
        "info",
        "infoself",
        "infoselftab",
        "infotab",
        "inspcombine",
        "inspdelete",
        "inspexecname",
        "inspexecpetname",
        "inspexecpettarget",
        "inspexecslot",
        "inspexectray",
        "inspirationslot",
        "interact",
        "invite",
        "k",
        "keybindreset",
        "kick",
        "kiosk",
        "l",
        "lc",
        "league",
        "leaguechat",
        "leagueinvite",
        "leaguekick",
        "leaguemakeleader",
        "leagueToggleTeamLock",
        "leagueWithdrawTeam",
        "leaveLeague",
        "leaveteam",
        "left",
        "lfg",
        "lfgeventresponse",
        "lfgremovefromqueue",
        "lfgrequesteventlist",
        "lfgset",
        "lfgtoggle",
        "li",
        "linkchannel",
        "linkinfo",
        "linkinteract",
        "linkinteractglobal",
        "listenrange",
        "lk",
        "lml",
        "loc",
        "local",
        "localtime",
        "lodbias",
        "logchat",
        "lookdown",
        "lookingforgroup",
        "lookup",
        "loudstacking",
        "ma",
        "macro",
        "macroimage",
        "macroslot",
        "mailview",
        "makeleader",
        "manage",
        "map",
        "maxAniso",
        "maxColorTrackerVerts",
        "maxfps",
        "maximize",
        "maxInactiveFps",
        "maxrtframes",
        "maxtexunits",
        "me",
        "menu",
        "mergeInsp",
        "missionarchitect",
        "missionmake",
        "missionsearch",
        "ml",
        "mmentry",
        "mmscrollsettoggleregion",
        "mmscrollsetviewlist",
        "monitorattribute",
        "mousedrag",
        "mouseinvert",
        "mouselook",
        "mousespeed",
        "myhandle",
        "mypurchases",
        "namecaptain",
        "namecommander",
        "nameenforcer",
        "nameflunky",
        "nameleader",
        "namelieutenant",
        "namemember",
        "nameoverlord",
        "nameringleader",
        "namescale",
        "nametaskmaster",
        "nav",
        "neterrorcorrection",
        "netgraph",
        "nexttray",
        "nexttrayalt",
        "nexttrayalt2",
        "nexttraystray",
        "noBump",
        "nojpg",
        "nojumprepeat",
        "nop",
        "noparticles",
        "nosunflare",
        "notga",
        "optionlist",
        "optionload",
        "optionloadfile",
        "optionsave",
        "optionsavefile",
        "optionset",
        "optiontoggle",
        "p",
        "petcom",
        "petcomall",
        "petcomname",
        "petcompow",
        "petition",
        "petoptions",
        "petrename",
        "petrenamename",
        "petsay",
        "petsayall",
        "petsayname",
        "petsaypow",
        "petselect",
        "petselectname",
        "playernote",
        "playernotelocal",
        "playerturn",
        "popmenu",
        "powers",
        "powerstogglealloff",
        "powexecabort",
        "powexecalt2slot",
        "powexecaltslot",
        "powexecauto",
        "powexeclocation",
        "powexecname",
        "powexecserverslot",
        "powexecslot",
        "powexectoggleoff",
        "powexectoggleon",
        "powexectray",
        "powexecunqueue",
        "prevshaders",
        "prevtray",
        "prevtrayalt",
        "prevtrayalt2",
        "prevtraystray",
        "private",
        "profilerrecord",
        "profilerstop",
        "profilingmemory",
        "promote",
        "quickchat",
        "quit",
        "quittocharacterselect",
        "quittologin",
        "r",
        "rechargeindicator",
        "rechargetimercolor",
        "rechargetimerformat",
        "rechargetimeropacity",
        "rechargetimerthreshold",
        "reducemip",
        "release",
        "releasepets",
        "reloadgfx",
        "renderscale",
        "renderscalex",
        "renderscaley",
        "rendersize",
        "reply",
        "req",
        "request",
        "requestexitmission",
        "respec",
        "respecstatus",
        "right",
        "roleplaying",
        "roll",
        "roomclip",
        "roomclipcycle",
        "rotate",
        "s",
        "salvageopen",
        "say",
        "screen",
        "screenshot",
        "screenshottga",
        "screenshottitle",
        "screenshotui",
        "sea",
        "search",
        "seeeverything",
        "selectbuild",
        "selectlast",
        "selectnext",
        "sell",
        "send",
        "servertime",
        "setdifficultyav",
        "setdifficultyboss",
        "setdifficultylevel",
        "setdifficultyteamsize",
        "sethelperstatus",
        "setpowerinfoclass",
        "settitle",
        "settitleid",
        "sg",
        "sgenterpasscode",
        "sgi",
        "sginvite",
        "sgk",
        "sgkick",
        "sgkickyes",
        "sgleave",
        "sgmode",
        "sgmodeset",
        "sgmusic",
        "sgpasscode",
        "sgsetdemotetimeout",
        "sgsetdescription",
        "sgsetmotd",
        "sgsetmotto",
        "sgwho",
        "shaderCache",
        "sheathe",
        "show",
        "showbind",
        "showbindall",
        "showbindallfile",
        "showfps",
        "shownewtray",
        "showpetnames",
        "showtime",
        "slashchat",
        "speakrange",
        "speedturn",
        "startchat",
        "stopinactivedisplay",
        "stopmonitorattribute",
        "stuck",
        "supergroup",
        "supporthardwarelights",
        "suppressCloseFx",
        "suppressCloseFxDist",
        "sync",
        "synch",
        "t",
        "tabclose",
        "tabcreate",
        "tabglobalnext",
        "tabglobalprev",
        "tabnext",
        "tabprev",
        "tabselect",
        "tabtoggle",
        "tailorstatus",
        "target",
        "targetcustomfar",
        "targetcustomnear",
        "targetcustomnext",
        "targetcustomprev",
        "targetdistance",
        "targetenemyfar",
        "targetenemynear",
        "targetenemynext",
        "targetenemyprev",
        "targetfriendfar",
        "targetfriendnear",
        "targetfriendnext",
        "targetfriendprev",
        "targetname",
        "team",
        "teamMoveToLeague",
        "teamquitinternal",
        "teamselect",
        "tell",
        "telllast",
        "texaniso",
        "texLodBias",
        "third",
        "thumbtack",
        "titlechange",
        "tl",
        "tll",
        "tmtl",
        "toggle",
        "toggleenemy",
        "toggleenemyprev",
        "trade",
        "tradeaccept",
        "tray",
        "trayalwaysshrink",
        "trayanimations",
        "traylabels",
        "traysticky",
        "traystickyalt2",
        "ttl",
        "turnleft",
        "turnright",
        "tutvotekick",
        "tutvotekickopinion",
        "uiscale",
        "unbind",
        "unbindall",
        "unfriend",
        "unhide",
        "unhideall",
        "unhidefriends",
        "unhidegchannels",
        "unhidegfriends",
        "unhideinvite",
        "unhidesearch",
        "unhidesg",
        "unhidetell",
        "unignore",
        "unlevelingpact",
        "unloadgfx",
        "unselect",
        "up",
        "usecelshader",
        "useCubemap",
        "usedof",
        "usefp",
        "usehdr",
        "useHQ",
        "userenderscale",
        "usewater",
        "visscale",
        "watching",
        "wdwload",
        "wdwloadfile",
        "wdwsave",
        "wdwsavefile",
        "wentworths",
        "whereami",
        "whisper",
        "who",
        "whoall",
        "windowcloseextra",
        "windowcolor",
        "windowhide",
        "windownames",
        "windowresetall",
        "windowscale",
        "windowshow",
        "windowtoggle",
        "y",
        "yell",
        "z",
        "zoomin",
        "zoomout",
    ]

    ### Initialization
    def __init__ (self, slash_command_string: str):
        """Initialize the slash command with a string."""
        self._slash_command_string = None
        self.slash_command_string = slash_command_string

    ### Properties
    @property
    def slash_command_string(self) -> str:
        return self._slash_command_string
    
    @slash_command_string.setter
    def slash_command_string(self, slash_command_string: str):
        formatted_slash_command_string = self._lowercase_first_word(string=slash_command_string)
        self._throw_error_on_invalid_slash_command_string(slash_command_string=formatted_slash_command_string)
        self._slash_command_string = formatted_slash_command_string

    @property
    def command(self) -> str:
        return self._get_slash_command_from_slash_command_string(slash_command_string=self.slash_command_string)
    
    @command.setter
    def command(self, command_string: str):
        formatted_command_string = command_string.lower()
        self._throw_error_on_invalid_slash_command(slash_command=formatted_command_string)
        if self.args:
            self._slash_command_string = f"{formatted_command_string} {self.args}"
        else:
            self._slash_command_string = formatted_command_string

    @property
    def args(self) -> str:
        return self._get_args_from_slash_command_string(self.slash_command_string)
    
    @args.setter
    def args(self, args: str):
        if args:
            self._slash_command_string = f"{self.command} {args}"
        else:
            self._slash_command_string = self.command

    ### Methods
    def _lowercase_first_word(self, string: str) -> str:
        """Helper function to lowercase the first word of the slash command string."""
        first_word, space, rest = string.partition(' ')
        return first_word.lower() + space + rest

    def _get_slash_command_from_slash_command_string(self, slash_command_string: str) -> str:
        """Helper function to extract the slash command from the slash command string."""
        return slash_command_string.split(' ')[0]
    
    def _get_args_from_slash_command_string(self, slash_command_string: str) -> str:
        """Helper function to extract the args from the slash command string."""
        args = slash_command_string.split(' ')[1:]
        return ' '.join(args) if args else ''

    ### Error Checking/Validation
    def _throw_error_on_invalid_slash_command_string(self, slash_command_string: str):
        """Helper function to validate the overall slash command string format."""
        self._throw_error_on_invalid_slash_command_string_format(slash_command_string=slash_command_string)

        slash_command = self._get_slash_command_from_slash_command_string(slash_command_string=slash_command_string)
        self._throw_error_on_invalid_slash_command(slash_command=slash_command)

        # no check on args needed, args can be anything

    def _throw_error_on_invalid_slash_command_string_format(self, slash_command_string: str):
        """Helper function to validate the overall slash command string format."""
        slash_command_pattern = r"^\w+(\s\w+)*$" # pattern to match "<slash_command> [args...]"
        if not re.match(slash_command_pattern, slash_command_string):
            raise ValueError(f"Invalid slash command format '{slash_command_string}'. Format should be \"<slash_command> [args...]\"")
        
    def _throw_error_on_invalid_slash_command(self, slash_command: str):
        """Helper function to validate the slash command portion of the slash command string."""
        minimal_slash_command = slash_command.replace('_', '')
        if minimal_slash_command not in self.VALID_COMMANDS:
            raise ValueError(f"Unknown slash command '{slash_command}'. Please see https://homecoming.wiki/wiki/List_of_Slash_Commands for a list of valid slash commands.")

    ### Overrides
    def __repr__(self):
        if self.args:
            return f"SlashCommand(command='{self.command}', args='{self.args}')"
        else:
            return f"SlashCommand(command='{self.command}')"
        
    def __str__(self):
        return self.slash_command_string
    
    def __eq__(self, other):
        if not isinstance(other, SlashCommand):
            return False
        return self.slash_command_string == other.slash_command_string
    